@baseUrl = http://localhost:3000

###
GET {{baseUrl}}/api/appointments

###
GET {{baseUrl}}/api/appointments?status=scheduled

###
GET {{baseUrl}}/api/appointments/1

###
GET {{baseUrl}}/api/appointments/999

###
POST {{baseUrl}}/api/appointments
Content-Type: application/json

{
  "patientId": 1,
  "doctorName": "Козлов Игорь Львович",
  "date": "2026-09-15",
  "time": "11:00"
}

###
POST {{baseUrl}}/api/appointments
Content-Type: application/json

{}

###
PUT {{baseUrl}}/api/appointments/4
Content-Type: application/json

{
  "patientId": 2,
  "doctorName": "Козлов Игорь Львович",
  "date": "2026-09-16",
  "time": "13:30",
  "status": "completed"
}

###
PUT {{baseUrl}}/api/appointments/999
Content-Type: application/json

{
  "patientId": 1,
  "doctorName": "Нет Такого",
  "date": "2026-09-16",
  "time": "13:30"
}

###
DELETE {{baseUrl}}/api/appointments/4

###
DELETE {{baseUrl}}/api/appointments/4

###
GET {{baseUrl}}/api/patients

###
GET {{baseUrl}}/api/patients/1

###
GET {{baseUrl}}/api/patients/999

###
POST {{baseUrl}}/api/patients
Content-Type: application/json

{
  "fullName": "Новиков Денис Олегович",
  "birthDate": "1995-07-19",
  "medicalRecord": {
    "bloodType": "AB(IV) Rh+",
    "allergies": [],
    "diagnoses": []
  }
}

###
POST {{baseUrl}}/api/patients
Content-Type: application/json

{
  "birthDate": "1995-07-19"
}

###
PUT {{baseUrl}}/api/patients/3
Content-Type: application/json

{
  "fullName": "Новиков Денис Олегович",
  "birthDate": "1995-07-19",
  "medicalRecord": {
    "bloodType": "AB(IV) Rh+",
    "allergies": ["йод"],
    "diagnoses": ["ОРВИ"]
  }
}

###
DELETE {{baseUrl}}/api/patients/3

###
GET {{baseUrl}}/api/doctors

